{"name": "test_add", "status": "failed", "statusDetails": {"message": "AssertionError: assert 8 == 7", "trace": "def test_add():\n        ret = add(3, 4)\n        expected = 8\n        # if ret == expected:\n        #     print(\"测试通过\")\n        # else:\n        #     print(\"测试不通过\")\n        # try:\n        #     assert expected == ret\n        # except AssertionError as e:\n        #     logging.error(\"断言失败:\", e)\n>       assert expected == ret\nE       assert 8 == 7\n\ntest_demo13.py:18: AssertionError"}, "attachments": [{"name": "stdout", "source": "b367b5a0-9883-4fab-9ef9-011126ae29d5-attachment.txt", "type": "text/plain"}], "start": 1618331561159, "stop": 1618331561160, "uuid": "cb3e3718-88bc-4532-8d31-e22402dc083b", "historyId": "b08460c77988aa40878b543742705e5d", "testCaseId": "87d19a6b5cdd5001fea2ce99068a77f8", "fullName": "test_demo13#test_add", "labels": [{"name": "suite", "value": "test_demo13"}, {"name": "host", "value": "GY"}, {"name": "thread", "value": "13884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo13"}]}